### ISSUE TITLE
'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by vphelipe** [x25/coinhive-stratum-mining-proxy#12]
2017-10-04 09:41:07-0400 [ProxyClient,client] Server -> Queue: {"jsonrpc":"2.0","error":{"code":-42,"message":"Timeout"},"result":null}
2017-10-04 09:41:07-0400 [ProxyClient,client] Unhandled Error
        Traceback (most recent call last):
          File "/usr/local/lib/python2.7/dist-packages/twisted/python/log.py", line 101, in callWithLogger
            return callWithContext({"system": lp}, func, *args, **kw)
          File "/usr/local/lib/python2.7/dist-packages/twisted/python/log.py", line 84, in callWithContext
            return context.call({ILogContext: newCtx}, func, *args, **kw)
          File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
            return self.currentContext().callWithContext(ctx, func, *args, **kw)
          File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
            return func(*args,**kw)
        --- <exception caught here> ---
          File "/usr/local/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
            why = selectable.doRead()
          File "/usr/local/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 209, in doRead
            return self._dataReceived(data)
          File "/usr/local/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 215, in _dataReceived
            rval = self.protocol.dataReceived(data)
          File "/usr/local/lib/python2.7/dist-packages/twisted/protocols/basic.py", line 454, in dataReceived
            self.lineReceived(line)
          File "x.py", line 101, in lineReceived
            elif data.get('result', {}).get('status') == 'OK':
        exceptions.AttributeError: 'NoneType' object has no attribute 'get'

**Comment by isaack0815** [comment]
i have the same problem

**Comment by samsonbro** [comment]
how to reduce threads,, to reduce the hashing speed,please advice sir.

**Comment by samsonbro** [comment]
how to reduce threads,, to reduce the hashing speed,please advice sir.
