### ISSUE TITLE
Erro on client connect

### ISSUE THREAD

**Issue by vphelipe** [x25/coinhive-stratum-mining-proxy#5]
2017-10-02 08:11:54-0700 [HTTPChannel,41,191.223.15.46] Client connected ({"peer
": "tcp4:191.223.15.46:57469", "headers": {"host": "107.**.**.201:8892", "conn
ection": "Upgrade", "pragma": "no-cache", "cache-control": "no-cache", "upgrade"
: "websocket", "origin": "http://107.**.**.201:8892", "sec-websocket-version":
"13", "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.
36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36", "accept-encoding": "
gzip, deflate", "accept-language": "en-US,en;q=0.8,pt-BR;q=0.6,pt;q=0.4,fr;q=0.2
,es-419;q=0.2,es;q=0.2", "sec-websocket-key": "JSmtdQsqlIZpVyphYL3Okg==", "sec-w
ebsocket-extensions": "permessage-deflate; client_max_window_bits"}, "host": "10
7.**.**.201", "path": "/proxy", "params": {}, "version": 13, "origin": "http:/
/107.**.**.201:8892", "protocols": [], "extensions": [["permessage-deflate", {
"client_max_window_bits": [true]}]]})
2017-10-02 08:11:54-0700 [HTTPChannel,41,191.223.15.46] WebSocket is open
2017-10-02 08:11:54-0700 [-] Starting factory <main.ProxyClientFactory objec
t at 0x000000BDB4136828>
2017-10-02 08:11:54-0700 [Uninitialized] Server connected
2017-10-02 08:11:54-0700 [Uninitialized] Queue -> Server: {"method": "login", "p
arams": {"login": "43AVtFt8zhaTE2CgR3sEBoBob5AFTg65kTM51CUAZukdhFcKxuZeesWe8MRUW
V4scE6bqe3BaarXYCxpCUEqLLGyE5bgoZW.worker", "pass": "x"}, "id": 1}
2017-10-02 08:11:54-0700 [-] Unhandled error in Deferred:
2017-10-02 08:11:54-0700 [-] Unhandled Error
Traceback (most recent call last):
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\li
b\site-packages\twisted\internet\protocol.py", line 494, in makeConnection
self.connectionMade()
File "coinhive-stratum-mining-proxy.py", line 60, in connectionMade
self.factory.di.to_server.get().addCallback(self.dataEnqueued)
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\li
b\site-packages\twisted\internet\defer.py", line 317, in addCallback
callbackKeywords=kw)
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\li
b\site-packages\twisted\internet\defer.py", line 306, in addCallbacks
self._runCallbacks()
--- ---
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\li
b\site-packages\twisted\internet\defer.py", line 588, in _runCallbacks
current.result = callback(current.result, *args, **kw)
File "coinhive-stratum-mining-proxy.py", line 75, in dataEnqueued
self.transport.write(data)
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\li
b\site-packages\twisted\internet\abstract.py", line 348, in write
raise TypeError("Data must not be unicode")
builtins.TypeError: Data must not be unicode

**Comment by vphelipe** [comment]
solution: python 2

**Comment by x25** [comment]
added python3 support
